#pragma once

#include <windows.h>

namespace ColorsText
{
    enum TextColor : WORD
    {
        BLACK = 0,
        BLUE = FOREGROUND_BLUE,
        GREEN = FOREGROUND_GREEN,
        CYAN = FOREGROUND_GREEN | FOREGROUND_BLUE,
        RED = FOREGROUND_RED,
        MAGENTA = FOREGROUND_RED | FOREGROUND_BLUE,
        YELLOW = FOREGROUND_RED | FOREGROUND_GREEN,
        WHITE = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE,
        GRAY = FOREGROUND_INTENSITY,
        LIGHT_BLUE = FOREGROUND_BLUE | FOREGROUND_INTENSITY,
        LIGHT_GREEN = FOREGROUND_GREEN | FOREGROUND_INTENSITY,
        LIGHT_CYAN = FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY,
        LIGHT_RED = FOREGROUND_RED | FOREGROUND_INTENSITY,
        LIGHT_MAGENTA = FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY,
        LIGHT_YELLOW = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY,
    };
}

namespace ColorsBackground
{
    enum BackgroundColor : WORD
    {
        BLACK = 0,
        BLUE = BACKGROUND_BLUE,
        GREEN = BACKGROUND_GREEN,
        CYAN = BACKGROUND_GREEN | BACKGROUND_BLUE,
        RED = BACKGROUND_RED,
        MAGENTA = BACKGROUND_RED | BACKGROUND_BLUE,
        YELLOW = BACKGROUND_RED | BACKGROUND_GREEN,
        WHITE = BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE,
        GRAY = BACKGROUND_INTENSITY,
        LIGHT_BLUE = BACKGROUND_BLUE | BACKGROUND_INTENSITY,
        LIGHT_GREEN = BACKGROUND_GREEN | BACKGROUND_INTENSITY,
        LIGHT_CYAN = BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY,
        LIGHT_RED = BACKGROUND_RED | BACKGROUND_INTENSITY,
        LIGHT_MAGENTA = BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY,
        LIGHT_YELLOW = BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY,
    };
}   

class ColorChanger
{
public:
    static void SetConsoleColor(
        WORD textColor = ColorsText::TextColor::WHITE, 
        WORD backgroundColor = ColorsBackground::BackgroundColor::BLACK
    );
};